import type { Db } from 'mongodb';
import { DECIDED_STATUSES, TRANSACTIONS_COLLECTION } from '../mastra/schemas/transactions';

/**
 * Demo-replay isolation.
 *
 * A recorded run lives in four "working" collections that the LIVE pipeline also writes to and
 * that a live reset clears. If demo mode read straight from those, a single live run (or reset)
 * would corrupt or destroy the recording — which is exactly what happens when someone switches
 * between modes on the same cluster.
 *
 * So `pnpm bake` snapshots the recording into dedicated, immutable `replay_*` collections. Demo
 * mode reads ONLY from those; live runs and resets never touch them. The two modes can now coexist
 * on one cluster indefinitely.
 */

/** The working collections the pipeline writes to during a run (and a live reset clears). */
export const RECORDING_COLLECTIONS = ['agent_events', 'case_analysis', 'reviews', 'audit_trail'] as const;
export type RecordingCollection = (typeof RECORDING_COLLECTIONS)[number];

/** Immutable replay copies, read in demo mode. Never written at runtime — only by `pnpm bake`. */
export const REPLAY_COLLECTIONS: Record<RecordingCollection, string> = {
  agent_events: 'replay_events',
  case_analysis: 'replay_analysis',
  reviews: 'replay_reviews',
  audit_trail: 'replay_audit',
};

export interface RecordingSource { events: string; analysis: string; reviews: string; audit: string }

/** Collection names the read APIs should use for recorded content, given the runtime mode. */
export function recordingSource(demoMode: boolean): RecordingSource {
  return demoMode
    ? {
        events: REPLAY_COLLECTIONS.agent_events, analysis: REPLAY_COLLECTIONS.case_analysis,
        reviews: REPLAY_COLLECTIONS.reviews, audit: REPLAY_COLLECTIONS.audit_trail,
      }
    : { events: 'agent_events', analysis: 'case_analysis', reviews: 'reviews', audit: 'audit_trail' };
}

/**
 * Provenance for the recording, written at snapshot time and carried with the exported artifact.
 *
 * WHY THE CORPUS SIZE TRAVELS WITH THE RECORDING. A replay is a recording of a run that happened
 * somewhere else, and the scale it ran at is a property of THAT run — not of whatever cluster is
 * replaying it. Every other number demo mode reports already comes from the recording, because the
 * read APIs route through `recordingSource()`; `counts.transactions` was the last one still read
 * live, so a recorded 1M run replayed on a 12k cluster reported 12k and understated the run it was
 * showing. Recording the number here is what makes demo mode self-consistent.
 *
 * This is also why the replay cluster does NOT need the corpus the recording ran against. Loading a
 * million documents onto a box that only ever replays would cost disk and seeding time to answer one
 * `estimatedDocumentCount()` — and it would create a hazard that not loading them avoids: synthetic
 * ids are positional (`txn-syn-00016`), so the SAME id means a different transaction in two corpora
 * generated by different revisions of the generator. Measured: `txn-syn-00016` is
 * `structuring`/escalated in the 12k corpus and `clean_approve`/approved in the 1M one. The
 * recording stores precedent content inline, so it renders correctly either way — but a cluster
 * holding look-alike documents would let `checkReplayHealth`'s dangling-id check pass while every
 * cited id silently pointed at something else.
 */
/**
 * Who produced the recording — the three things its numbers are not portable across.
 *
 * The recording is not just a script of what happened; demo mode publishes its timings as
 * `latency_p50_ms` and its per-stage tail in the status bar. Those are performance claims, and a
 * performance claim without provenance cannot be checked or reproduced. `corpus_size` alone answers
 * "at what scale" and leaves "on what hardware, at what revision, with which model" unanswerable.
 *
 * This is the same discipline `buildManifest` already applies to the benchmark corpus
 * (scripts/bench-corpus.ts): tier and app commit travel WITH the artifact, because the artifact
 * outlives the shell session that knows them. Measured cost of not doing it: attributing the
 * 2026-07-27 recording meant reading `git reflog` on the box and matching a checkout timestamp
 * against `recorded_at` — recoverable that day, and not recoverable after the box is replaced.
 *
 * Every field is a plain string, 'unknown' when it could not be determined, and never absent — on
 * the way in AND on the way out (`readReplayMeta` fills it for artifacts baked before these fields
 * existed). A caller reading `meta.app_commit` must get something printable without a guard;
 * 'unknown' is a legible answer to "which commit?" and `undefined` renders as a blank where a reader
 * would take the absence for a value.
 */
export interface ReplayProvenance {
  /** App commit the recording was produced at — short hash, or 'unknown'. */
  app_commit: string;
  /**
   * Atlas tier of the source cluster (e.g. 'M30'), or 'unknown'.
   *
   * Load-bearing for the same reason `benchmark_tier` is: a second 1M vector index on one M30 moved
   * an untouched index's p50 from 21.0 to 179.6 ms. Latency read off a recording says nothing
   * without the tier it was read on.
   */
  atlas_tier: string;
  /**
   * LLM that produced the verdicts, from `LLM_MODEL`.
   *
   * The dominant term in the recorded span — a full run is ~10.4 s, of which the model is most —
   * so a recording re-baked on a different model is a different measurement, not a fresher one.
   */
  llm_model: string;
}

export interface ReplayMeta extends ReplayProvenance {
  /** Documents in `transactions` on the cluster the recording was produced against. */
  corpus_size: number;
  /**
   * Decided (non-pending) documents in that same corpus, as of the moment the run STARTED.
   *
   * Recorded alongside `corpus_size` because the two are displayed side by side in the status bar.
   * Carrying one without the other renders "corpus 1,000,015 · precedents 12,009" — two numbers
   * from two different clusters, presented as one reading.
   *
   * "As of the moment the run started" is the load-bearing part, and it is not what a naive count
   * gives you — see `snapshotReplay`. A replay depicts a queue of undecided cases being worked, so
   * the precedent count it publishes has to be the one that was true while they were still
   * undecided. `status` partitions exactly into `pending` + DECIDED_STATUSES, so a reader can and
   * will check the arithmetic: `corpus_size - decided_precedents` must equal the number of cases the
   * recording covers.
   */
  decided_precedents: number;
  /** Database the run was recorded on — the provenance a reader needs to check the claim. */
  source_db: string;
  recorded_at: Date;
}

/** Single-document collection: the recording's provenance, exported and restored with it. */
export const REPLAY_META_COLLECTION = 'replay_meta';

/**
 * Snapshot every working recording collection into its immutable replay copy (drop + copy,
 * preserving `_id`), then record the run's provenance. Idempotent — safe to run after every bake.
 * Returns per-collection doc counts.
 */
export async function snapshotReplay(
  db: Db, provenance: ReplayProvenance,
): Promise<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const src of RECORDING_COLLECTIONS) {
    const dst = REPLAY_COLLECTIONS[src];
    const docs = await db.collection(src).find({}).toArray();
    await db.collection(dst).deleteMany({});
    if (docs.length) await db.collection(dst).insertMany(docs);
    counts[dst] = docs.length;
  }

  // Captured from the SOURCE cluster, while we are still connected to it — this is the only moment
  // the recorded scale is knowable. `countDocuments` rather than `estimatedDocumentCount` because
  // this runs once per bake and the number is about to be published as a claim.
  const tx = db.collection(TRANSACTIONS_COLLECTION);

  // The cases this recording covers. Excluded from the decided tally below, because this function
  // runs AFTER the run it is freezing: by now the pipeline has written each case's disposition back
  // to `transactions.status`, so a bare decided-count measures the cluster the run LEFT BEHIND while
  // publishing it as the corpus the run was performed AGAINST.
  //
  // Measured cost of getting this wrong: the 2026-07-27 artifact recorded 1,000,012 decided out of
  // 1,000,015 for a 6-case recording. Three of the six had committed their verdicts and three were
  // still held at the human gate, so the counter saw 3 pending instead of 6 and the status bar
  // published a corpus that was three documents short of accounting for its own queue. `status`
  // partitions exactly into `pending` + DECIDED_STATUSES (see TransactionSchema), so the missing
  // documents were not hiding in a third state — the number was simply off by the cases that had
  // finished first.
  //
  // `$nin` on the recorded ids rather than resetting the queue and re-counting: this is derived from
  // the recording itself, so it is right for any recording of any size and does not depend on an
  // operator sequencing a reset before the snapshot — which is precisely the step that failed.
  const recordedIds = (await db.collection(REPLAY_COLLECTIONS.case_analysis)
    .find({}, { projection: { _id: 0, transaction_id: 1 } })
    .toArray())
    .map(d => (d as { transaction_id?: unknown }).transaction_id)
    .filter((id): id is string => typeof id === 'string' && id !== '');

  const meta: ReplayMeta = {
    corpus_size: await tx.countDocuments({}),
    // Same predicate `gatherStats` uses for the live number, so the recorded and live figures are
    // the same measurement — not two definitions of "decided" that happen to be close. The `$nin` is
    // the one deliberate difference, and it is what makes this the count as-of the run's start.
    decided_precedents: await tx.countDocuments({
      status: { $in: [...DECIDED_STATUSES] },
      ...(recordedIds.length ? { transaction_id: { $nin: recordedIds } } : {}),
    }),
    source_db: db.databaseName,
    recorded_at: new Date(),
    // Passed in rather than discovered here: the commit comes from git and the tier from the Atlas
    // Admin API, and this function must stay pure Db access so it is testable without either.
    ...provenance,
  };
  await db.collection(REPLAY_META_COLLECTION).deleteMany({});
  await db.collection(REPLAY_META_COLLECTION).insertOne(meta as never);
  counts[REPLAY_META_COLLECTION] = 1;

  return counts;
}

/**
 * Read the recording's provenance, or null when the artifact predates it.
 *
 * Null is a supported state, not an error: recordings exported before `replay_meta` existed restore
 * without it, and callers fall back to the live count. A demo that reports the replaying cluster's
 * own size is merely understated, which is a far better failure than refusing to start.
 */
export async function readReplayMeta(db: Db): Promise<ReplayMeta | null> {
  const doc = await db.collection(REPLAY_META_COLLECTION)
    .findOne<ReplayMeta>({}, { projection: { _id: 0 } })
    .catch(() => null);
  if (!doc || !Number.isFinite(doc.corpus_size)) return null;
  // Provenance is newer than `corpus_size`, so an artifact can carry the scale and not the rest.
  // Filled here rather than at each call site: the interface promises three printable strings, and a
  // reader that has to guard every field will eventually forget one and render a blank. Written as
  // per-field `??` rather than a defaults-then-spread literal because the type says these fields are
  // present — so the compiler flags the literal form as dead, while `??` states the actual runtime
  // fact, which is that an old document simply does not have them.
  return {
    ...doc,
    app_commit: doc.app_commit ?? 'unknown',
    atlas_tier: doc.atlas_tier ?? 'unknown',
    llm_model: doc.llm_model ?? 'unknown',
  };
}
