import type { Db } from 'mongodb';
import { DECIDED_STATUSES, TRANSACTIONS_COLLECTION } from '../mastra/schemas/transactions';

/**
 * Demo-replay isolation.
 *
 * A recorded run lives in four "working" collections that the LIVE pipeline also writes to and
 * that a live reset clears. If demo mode read straight from those, a single live run (or reset)
 * would corrupt or destroy the recording — which is exactly what happens when someone switches
 * between modes on the same cluster.
 *
 * So `pnpm bake` snapshots the recording into dedicated, immutable `replay_*` collections. Demo
 * mode reads ONLY from those; live runs and resets never touch them. The two modes can now coexist
 * on one cluster indefinitely.
 */

/** The working collections the pipeline writes to during a run (and a live reset clears). */
export const RECORDING_COLLECTIONS = ['agent_events', 'case_analysis', 'reviews', 'audit_trail'] as const;
export type RecordingCollection = (typeof RECORDING_COLLECTIONS)[number];

/** Immutable replay copies, read in demo mode. Never written at runtime — only by `pnpm bake`. */
export const REPLAY_COLLECTIONS: Record<RecordingCollection, string> = {
  agent_events: 'replay_events',
  case_analysis: 'replay_analysis',
  reviews: 'replay_reviews',
  audit_trail: 'replay_audit',
};

export interface RecordingSource { events: string; analysis: string; reviews: string; audit: string }

/** Collection names the read APIs should use for recorded content, given the runtime mode. */
export function recordingSource(demoMode: boolean): RecordingSource {
  return demoMode
    ? {
        events: REPLAY_COLLECTIONS.agent_events, analysis: REPLAY_COLLECTIONS.case_analysis,
        reviews: REPLAY_COLLECTIONS.reviews, audit: REPLAY_COLLECTIONS.audit_trail,
      }
    : { events: 'agent_events', analysis: 'case_analysis', reviews: 'reviews', audit: 'audit_trail' };
}

/**
 * Provenance for the recording, written at snapshot time and carried with the exported artifact.
 *
 * WHY THE CORPUS SIZE TRAVELS WITH THE RECORDING. A replay is a recording of a run that happened
 * somewhere else, and the scale it ran at is a property of THAT run — not of whatever cluster is
 * replaying it. Every other number demo mode reports already comes from the recording, because the
 * read APIs route through `recordingSource()`; `counts.transactions` was the last one still read
 * live, so a recorded 1M run replayed on a 12k cluster reported 12k and understated the run it was
 * showing. Recording the number here is what makes demo mode self-consistent.
 *
 * This is also why the replay cluster does NOT need the corpus the recording ran against. Loading a
 * million documents onto a box that only ever replays would cost disk and seeding time to answer one
 * `estimatedDocumentCount()` — and it would create a hazard that not loading them avoids: synthetic
 * ids are positional (`txn-syn-00016`), so the SAME id means a different transaction in two corpora
 * generated by different revisions of the generator. Measured: `txn-syn-00016` is
 * `structuring`/escalated in the 12k corpus and `clean_approve`/approved in the 1M one. The
 * recording stores precedent content inline, so it renders correctly either way — but a cluster
 * holding look-alike documents would let `checkReplayHealth`'s dangling-id check pass while every
 * cited id silently pointed at something else.
 */
export interface ReplayMeta {
  /** Documents in `transactions` on the cluster the recording was produced against. */
  corpus_size: number;
  /**
   * Decided (non-pending) documents in that same corpus.
   *
   * Recorded alongside `corpus_size` because the two are displayed side by side in the status bar.
   * Carrying one without the other renders "corpus 1,000,015 · precedents 12,009" — two numbers
   * from two different clusters, presented as one reading.
   */
  decided_precedents: number;
  /** Database the run was recorded on — the provenance a reader needs to check the claim. */
  source_db: string;
  recorded_at: Date;
}

/** Single-document collection: the recording's provenance, exported and restored with it. */
export const REPLAY_META_COLLECTION = 'replay_meta';

/**
 * Snapshot every working recording collection into its immutable replay copy (drop + copy,
 * preserving `_id`), then record the run's provenance. Idempotent — safe to run after every bake.
 * Returns per-collection doc counts.
 */
export async function snapshotReplay(db: Db): Promise<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const src of RECORDING_COLLECTIONS) {
    const dst = REPLAY_COLLECTIONS[src];
    const docs = await db.collection(src).find({}).toArray();
    await db.collection(dst).deleteMany({});
    if (docs.length) await db.collection(dst).insertMany(docs);
    counts[dst] = docs.length;
  }

  // Captured from the SOURCE cluster, while we are still connected to it — this is the only moment
  // the recorded scale is knowable. `countDocuments` rather than `estimatedDocumentCount` because
  // this runs once per bake and the number is about to be published as a claim.
  const tx = db.collection(TRANSACTIONS_COLLECTION);
  const meta: ReplayMeta = {
    corpus_size: await tx.countDocuments({}),
    // Same predicate `gatherStats` uses for the live number, so the recorded and live figures are
    // the same measurement — not two definitions of "decided" that happen to be close.
    decided_precedents: await tx.countDocuments({ status: { $in: [...DECIDED_STATUSES] } }),
    source_db: db.databaseName,
    recorded_at: new Date(),
  };
  await db.collection(REPLAY_META_COLLECTION).deleteMany({});
  await db.collection(REPLAY_META_COLLECTION).insertOne(meta as never);
  counts[REPLAY_META_COLLECTION] = 1;

  return counts;
}

/**
 * Read the recording's provenance, or null when the artifact predates it.
 *
 * Null is a supported state, not an error: recordings exported before `replay_meta` existed restore
 * without it, and callers fall back to the live count. A demo that reports the replaying cluster's
 * own size is merely understated, which is a far better failure than refusing to start.
 */
export async function readReplayMeta(db: Db): Promise<ReplayMeta | null> {
  const doc = await db.collection(REPLAY_META_COLLECTION)
    .findOne<ReplayMeta>({}, { projection: { _id: 0 } })
    .catch(() => null);
  return doc && Number.isFinite(doc.corpus_size) ? doc : null;
}
